# Generated by Django 4.2.17 on 2025-01-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
